INSERT INTO users (id, name, age) VALUES (1, 'Finnebar', 17)
INSERT INTO users (id, name, age) VALUES (2, 'Bear', 6)
INSERT INTO 
INSERT INTO users (id, name, age) VALUES users (id, name, age) VALUES (3, 'Iguana', 4)(1, 'Finnebar', 17)
INSERT INTO users (id, name, age) VALUES (1, 'Finnebar', 17)
INSERT INTO users (id, name, age) VALUES (1, 'Finnebar', 17)
INSERT INTO users (id, name, age) VALUES (1, 'Finnebar', 17)
INSERT INTO users (id, name, age) VALUES (1, 'Finnebar', 17)
INSERT INTO users (id, name, age) VALUES (1, 'Finnebar', 17)
INSERT INTO users (id, name, age) VALUES (1, 'Finnebar', 17)
INSERT INTO users (id, name, age) VALUES (1, 'Finnebar', 17)
INSERT INTO users (id, name, age) VALUES (1, 'Finnebar', 17)
INSERT INTO users (id, name, age) VALUES (1, 'Finnebar', 17)
INSERT INTO users (id, name, age) VALUES (1, 'Finnebar', 17)
INSERT INTO users (id, name, age) VALUES (1, 'Finnebar', 17)
INSERT INTO users (id, name, age) VALUES (1, 'Finnebar', 17)
INSERT INTO users (id, name, age) VALUES (1, 'Finnebar', 17)
INSERT INTO users (id, name, age) VALUES (1, 'Finnebar', 17)
INSERT INTO users (id, name, age) VALUES (1, 'Finnebar', 17)
INSERT INTO users (id, name, age) VALUES (1, 'Finnebar', 17)